export const data = [
    {
        id:1,
        name:'Spicy Paneer Pizza',
        price:'460',
        description: 'Spicy Paneer made with Kashmiri & Birds Eye Chilli Drizzled with our House Spicy Mayonnaise!',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/n2aj0plizotlisjfo0sk',
        category: 'pizza',
        quantity:0,
    },
    {
        id:2,
        name:'Margherita Pizza',
        price:'505',
        category: 'pizza',
        description: 'Our Original Sauce & Fresh Basil Leaves with Mozzarella',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/edfx8t507wwu5a8upzae',
        quantity:0,
    },
    {
        id:3,
        name:'The ABD Pizza',
        price:'595',
        category: 'pizza',
        description: 'Onion, Capsicum & Birds Eye Chilli on a Classic Margherita for an Extra Zing',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/kkznictwovakz5a17a4f',
        quantity:0,
    },
    {
        id:4,
        name:'Verdure Pizza',
        price:'705',
        category: 'pizza',
        description: 'Sicilian Olives, Bell Peppers, Sweet Corn Kernels, Mini Heirloom Tomatoes, Red Onions with Mozzarella Cheese',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/q7s1r7qyetdn7t0e1ncd',
        quantity:0,
    },
    {
        id:5,
        name:'The Pizza Davide',
        price:'640',
        category: 'pizza',
        description: 'An Elevation of the Classic Margherita with the Supplement of Roasted Garlic , Soft G.o.a.t Cheese and Our Signature Pesto Sauce with a Personal Touch of Italy',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/dyc0djjhnv0t7n5rpcly',
        quantity:0,
    },
    {
        id:6,
        name:'Pizza Ai Porcini',
        price:'730',
        category: 'pizza',
        description: 'Porcini Mushroom Ragout with Fresh Mozzarella Chilli, Lime and Truffle Oil',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/n2aj0plizotlisjfo0sk',
        quantity:0,
    },
    {
        id:7,
        name:'Fiamma Pizza',
        price:'595',
        category: 'pizza',
        description: 'Francescos Signature Fiama with onions and chilly Flakes',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/u9rr99a6wx4o4crj2jkf',
        quantity:0,
    },
    {
        id:8,
        name:'Fruits Of The Forest Pizza',
        price:'595',
        category: 'pizza',
        description: 'Thyme Flavoured Button Mushrooms with our Mozzarella & Parmesan Cheese',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/th9v9bbxmc4nmcifd4yo',
        quantity:0,
    },
    {
        id:9,
        name:'Insalata & Garden Pizza',
        price:'595',
        category: 'pizza',
        description: 'Margherita Topped with Rocket Leaf Salad, Balsamic Reduction, Heirloom Tomatoes & Pickled Onion Slices',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/knbfahivtneeeyb0mxsv',
        quantity:0,
    },
    {
        id:10,
        name:'Pasta In Our Rose Sauce',
        price:'450',
        category: 'Pastas',
        description: 'Best Of Both Worlds, A Blend Of Arrabiata And Cream Sauce',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/qfbveeyt2bdrl0cxe303',
        quantity:0,
    },
    {
        id:11,
        name:'Pasta In Our Creamy Cheese Sauce',
        price:'450',
        category: 'Pastas',
        description: 'Hand Made Creamy Cheese Sauce With The Pasta Of Your Choice',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/ufsy8hnclxxhaiohqmnv',
        quantity:0,
    },
    {
        id:12,
        name:'Ciaccolato Mousse',
        price:'195',
        category: 'Dolki',
        description: 'Chocolate mousse, the way you like it',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/q01qvq6ysenplwjedp2a',
        quantity:0,
    },
    {
        id:13,
        name:'Dipping Sauce',
        price:'150',
        category: 'Dolki',
        description: 'Creamy Garlic Dip',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/phbn2dkqj0empn9zww6j',
        quantity:0,
    },
    {
        id:14,
        name:'Cheesy Garlic Bread',
        price:'270',
        category: 'Starters',
        description: 'Our In House Mini Ciabatta Loaves Slathered with Herby Garlic Butter and Cheese',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/nv1c1qkmfelrsl6hyn0o',
        quantity:0,
    },
    {
        id:15,
        name:'Truffle Fries',
        price:'450',
        category: 'Starters',
        description: 'Crispy French Fries Sprinkled with a Blend of Aromatic Spices, Truffle Oil and Served with a Creamy Dip TRUFFLE OIL',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/ln9ytorfrpnwe6gjup0u',
        quantity:0,
    },
    {
        id:16,
        name:'Patatine Fritte',
        price:'230',
        category: 'Starters',
        description: 'Crispy French Fries Sprinkled with a Blend of Aromatic Spices and Served with Creamy Dip',
        image:'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/wtiklg9xcyqcipbgv7bg',
        quantity:0,
    },
    

];
